source:
  type: file # Can be 'file' or 'table'
  format: csv # For files: 'csv', 'json', etc. For tables: specify DB type 'PostgreSQL', 'MySQL', etc.
  name: local_data/input/sample_data.csv
destination:
  type: file
  format: csv
  name: local_data/output/processed_data.csv
destination_example:
  type: table
  format: mysql
  name: mysql_result_table
